volumes:
  kerberos-server-data:

services:
  kerberos-server:
    container_name: kerberos-server
    image: reprostat/kerberos-server-container:latest
    build: .
    environment:
      - REALM=example.com
      - KRB5_KDC=localhost
      - LDAP_URI=ldaps://10.10.10.10
      - LDAP_CACERT=/etc/ldap/ca.crt
      - LDAP_ADMIN_PASSWORD=adminpass
      - LDAP_KADMIN_PASSWORD=kadminpass
      - LDAP_KDC_PASSWORD=kdcpass
    ports:
      - 88:88
      - 464:464
      - 749:749
    volumes:
      - kerberos-server-data:/var/lib/krb5kdc
      - $PWD/ca.crt:/etc/ldap/ca.crt
